### ISSUE TITLE
live demo link is not working

### ISSUE THREAD

**Issue by khitermedachraf** [joseph07-drack/todo-list-app#8]
### **Hello @joseph07-drack 👋 you did Amazing work 🥇 .**
- Clean Code 👍 .
- Github workflow 👍 .

but I noticed that **the live demo link is not working**, there is a typo on the URL.

1. kindly fix that.

**Comment by jodrack07** [comment]
Thanks, @khitermedachraf, I am going to work on it.

**Comment by jodrack07** [comment]
Hey again @khitermedachraf , I just fixed the ```live demo link``` [click here to check it](https://joseph07-drack.github.io/todo-list-app/dist/)

**Comment by khitermedachraf** [comment]
### Awesome 😎, You did an amazing work with the app ✅.
**Keep going bro 🔥.**
